version: 0.0
os: linux
files:
  - source: /var/lib/jenkins/job/HippoBuild/ws/cms/target/cms.war
    destination: /usr/share/tomcat8/webapps
    source: /var/lib/jenkins/job/HippoBuild/ws/site/target/site.war
    destination: /usr/share/tomcat8/webapps
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
